# Introduction to Numpy

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python 

### Importing the library

In [1]:
import numpy as np

### Creating a Numpy array

In [4]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


### Dimensions of Numpy arrays

#### 0-D Array

In [7]:
arr_0 = np.array(7)
print(arr_0)
print(arr_0.ndim)

7
0


#### 1-D Arrays

In [9]:
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)
print("Dimensions:", arr_1.ndim)

[1 2 3 4 5]
Dimensions: 1


#### 2-D Arrays

In [10]:
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2)
print("Dimensions:", arr_2.ndim)

[[1 2 3]
 [4 5 6]]
Dimensions: 2


### Printing Elements of the Array

In [11]:
# Printing with 1-D Arrays
arr = np.array([1, 2, 3])
print(arr[1])

2


In [14]:
# Printing with 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])

6


In [15]:
# Print using -ve indexing
print(arr[-1, -1])

6


### Slicing

In [20]:
# Slicing by providing indices to 1-D Array
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[1:5])
print(arr[0:5])
print(arr[:])
print(arr[:-1])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5]


In [27]:
# Slicing by providing indices to 2-D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("First Row:", arr[0:1, :])
print("Second Row:", arr[1:, :])
print("Second Column:", arr[0:, 1:2])

[[1 2 3]
 [4 5 6]]
First Row: [[1 2 3]]
Second Row: [[4 5 6]]
Second Column: [[2]
 [5]]


### Stepping

In [36]:
# Stepping on 1-D Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[::2])
print(arr[1::2])
print(arr[3::2])

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 4  6  8 10]


In [49]:
# Stepping on 2-D Array
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [ 8, 9, 10, 11], [12, 13, 14, 15]])
print(arr)
print(arr[1::2,:])
print(arr[:,1::2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [12 13 14 15]]
[[ 2  4]
 [ 5  7]
 [ 9 11]
 [13 15]]


### Copying

In [52]:
# Copying by equal sign would make both arrays point to the same location
arr = np.array([1, 2, 3, 4, 5])
arr_b = arr
arr_b[1] = 7
print(arr)

[1 7 3 4 5]


In [53]:
# Should use copy to make a separate copy
arr = np.array([1, 2, 3, 4, 5])
arr_b = arr.copy()
arr_b[1] = 7
print(arr_b)
print(arr)

[1 7 3 4 5]
[1 2 3 4 5]


### Shape

In [55]:
# Shape in 1-D
arr = np.array([1, 2, 3, 4, 5])
print(arr.ndim)
print(arr.shape)

1
(5,)


In [59]:
# Shape in 2-D
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


### Reshaping

In [77]:
# 1-D to 2-D
arr = np.array([1, 2, 3, 4])
arr_1 = arr.reshape(2, 2)
print(arr_1)

[[1 2]
 [3 4]]


In [67]:
# 2-D to 1-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_1 = arr.reshape(-1)
print(arr_1)
print(arr_1.ndim)

[1 2 3 4 5 6]
1


### Joining Arrays

In [73]:
# Arrays can be concatenated
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
result = np.concatenate((arr_1, arr_2))
print(result)

[1 2 3 4 5 6]


In [76]:
# Arrays can be Stack
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
result = np.stack((arr_1, arr_2))
print(result)

[[1 4]
 [2 5]
 [3 6]]


### Searching in Arrays

In [80]:
# Searching for element in an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 4, 4])
result = np.where(arr == 4)
print(result)

(array([ 3, 10, 11], dtype=int64),)


In [81]:
# Searching using other conditions
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 4, 4])
result = np.where(arr%2==0)
print(result)

(array([ 1,  3,  5,  7,  9, 10, 11], dtype=int64),)


In [82]:
# Search and return values
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 4, 4])
result = arr[arr%2==0]
print(result)

[ 2  4  6  8 10  4  4]


### Vectors and Matrices

In [85]:
# Creating 3x3 matrix of 1's
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [87]:
# Creating 3x3 matrix of 0's
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [95]:
# Creating 3x3 matrix of random numbers between 0 and 1
arr = np.random.rand(3, 3)
print(arr)

[[0.63266949 0.10576481 0.74918834]
 [0.94185668 0.65129727 0.29140669]
 [0.25812954 0.32985874 0.5264229 ]]


In [98]:
# Creating 3x3 matrix of random numbers between 0 and 50
arr = np.random.randint(50, size=(3,3))
print(arr)

[[14  4 44]
 [29 21 28]
 [48 49 30]]


In [99]:
# Creating a row vector
arr = np.array([[1, 2, 3]])
print(arr)
print(arr.shape)

[[1 2 3]]
(1, 3)


In [100]:
# Creating a column vector (T is used to transpose)
arr = np.array([[1, 2, 3]]).T
print(arr)
print(arr.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [105]:
# Matrix Multiplication
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [3, 4]])
print(arr_1)
print(arr_2)

result = np.matmul(arr_1, arr_2)
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[11 14]
 [27 34]]


In [106]:
# Dot Product
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [3, 4]])
print(arr_1)
print(arr_2)

result = np.dot(arr_1, arr_2)
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[11 14]
 [27 34]]


In [110]:
# Identity Matrix
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
